### ISSUE TITLE
Warrior Hall bib draws on top of units

### ISSUE THREAD

**Issue by pchote** [IceReaper/OpenKrush#122]
<img width="406" alt="Screenshot 2021-03-10 at 22 33 02" src="https://user-images.githubusercontent.com/167819/110707122-c0b2a780-81f0-11eb-835c-0487522d9ffc.png">

**Comment by Dzierzan** [comment]
Is it possible to somehow swift it up somehow without breaking offsets, footprint and whatnot? What I exactly mean it making sure that the actor is behind the building if it "above" it.
