### ISSUE TITLE
Research buttton doesn't work properly

### ISSUE THREAD

**Issue by Dzierzan** [IceReaper/OpenKrush#133]
Apparently, if you click the research button (or use the hotkey) and then click on any building, the research won't be initiated. Instead the clicked building will be selected.

**Comment by IceReaper** [comment]
Whats the expected behavior on research / sell / repair when using leftaction button setup and which is expected on using right action button setup?

**Comment by Dzierzan** [comment]
If you switch to control scheme to "modern", it works fine. Either way, it should be working for "classic" too.

**Comment by IceReaper** [comment]
Fixed
