### ISSUE TITLE
Game over timer cut off

### ISSUE THREAD

**Issue by OndroNR** [IceReaper/OpenKrush#145]
At top of the screen

![image](https://user-images.githubusercontent.com/978340/111905320-50572200-8a4b-11eb-9636-f3b00bb3645d.png)

**Comment by OndroNR** [comment]
It is also shifted during replay

**Comment by OndroNR** [comment]
How do we override Y value in Container@GAME_TIMER_BLOCK in this long common YAML ?
https://github.com/OpenRA/OpenRA/blob/1a9dfc0893/mods/common/chrome/ingame-observer.yaml#L14

**Comment by IceReaper** [comment]
Fixed
