### ISSUE TITLE
Fatal Error (Windows)

### ISSUE THREAD

**Issue by LightningHelper** [IceReaper/OpenKrush#148]
Hi,
I've downloaded and installed playtest-20210316, but when I try to start it I see this:
![image](https://user-images.githubusercontent.com/35897350/123023663-c26e3880-d3a5-11eb-9b15-d4cb8aa428a9.png)
clicking on `View Logs` does not do anything.
Thanks
```
Edition	Windows 10 Pro
Version	21H1
Installed on	‎25-‎Jul-‎20
OS build	19043.1081
Experience	Windows Feature Experience Pack 120.2212.3920.0
```

**Comment by IceReaper** [comment]
Kknd installed via Steam or gog?

**Comment by LightningHelper** [comment]
Shame on me, I did not know that I need kknd installed - but maybe for other stupid people like me a better error message?

**Comment by IceReaper** [comment]
Implemented a better message ;)

**Comment by Austin28069** [comment]
![image](https://user-images.githubusercontent.com/89229193/130160685-5ce1a858-eca7-4495-ac5a-d4bcd3f220d1.png)
I installed KKnD via Steam. But it's often crashed while playing the game.

**Comment by IceReaper** [comment]
Got crashlogs for me? So i know what happened

**Comment by Austin28069** [comment]
Sure, which file do you need? In other words, how may I get the crashlogs for you?
![image](https://user-images.githubusercontent.com/89229193/130204020-5c3dedf0-2928-4565-b910-0965970e1e30.png)
Moreover, how may I send these files to you?

**Comment by Dzierzan** [comment]
The latest exception.log file. You can literally drag and drop the file here.

**Comment by IceReaper** [comment]
Best would be all of them. Might be different crash reasons.

**Comment by Austin28069** [comment]
Thank you!!
[exception-2021-08-17T061007Z.log](https://github.com/IceReaper/OpenKrush/files/7020335/exception-2021-08-17T061007Z.log)
[exception-2021-08-19T165448Z.log](https://github.com/IceReaper/OpenKrush/files/7020336/exception-2021-08-19T165448Z.log)
[exception-2021-08-19T181713Z.log](https://github.com/IceReaper/OpenKrush/files/7020337/exception-2021-08-19T181713Z.log)
[exception-2021-08-19T210020Z.log](https://github.com/IceReaper/OpenKrush/files/7020338/exception-2021-08-19T210020Z.log)
[exception-2021-08-19T211359Z.log](https://github.com/IceReaper/OpenKrush/files/7020339/exception-2021-08-19T211359Z.log)
[exception-2021-08-19T214734Z.log](https://github.com/IceReaper/OpenKrush/files/7020340/exception-2021-08-19T214734Z.log)
[exception-2021-08-19T223800Z.log](https://github.com/IceReaper/OpenKrush/files/7020341/exception-2021-08-19T223800Z.log)
[exception-2021-08-20T002807Z.log](https://github.com/IceReaper/OpenKrush/files/7020342/exception-2021-08-20T002807Z.log)
[exception-2021-08-20T011750Z.log](https://github.com/IceReaper/OpenKrush/files/7020343/exception-2021-08-20T011750Z.log)

**Comment by IceReaper** [comment]
Allright, 2 different reasons thanks :) Ill reproduce them and close this issue when both are fixed.

**Comment by Austin28069** [comment]
Wow!! That's impressive!!
I really appreciate your help!
I am looking forward to using your platform to play KKnD with my friends.

**Comment by IceReaper** [comment]
Fixed in latest commit.

**Comment by Austin28069** [comment]
Great!!
I tried to re-download version: 20210316, but it's also crashed again.
How to download the fixed version?
![image](https://user-images.githubusercontent.com/89229193/130336843-31c9d5c4-e420-4b22-8991-db2cae5da1e1.png)
[exception-2021-08-21T225431Z.log](https://github.com/IceReaper/OpenKrush/files/7026323/exception-2021-08-21T225431Z.log)

**Comment by IceReaper** [comment]
Next release has it included

**Comment by Austin28069** [comment]
It's very nice of you.
Thank you for your reply.
