### ISSUE TITLE
Crashing at startup on MacOS

### ISSUE THREAD

**Issue by wu3ty** [IceReaper/OpenKrush#154]
OpenKrush is crashing on MacOS when running latest version through Terminal (compiled latest master branch using _make_).  After a short switch to a black fullscreen view, I am receiving following error on console:
```
Platform is OSX
Engine version is 58d0f639456953662f5fc952825b01e7a5aeb0b1
Runtime: .NET CLR 5.0.6
Using SDL 2 with OpenGL (Modern) renderer
Desktop resolution: 1440x900
No custom resolution provided, using desktop resolution
Using resolution: 1440x900
Using window scale 2.00
./launch-game.sh: line 55: 28047 Illegal instruction: 4  ${RUNTIME_LAUNCHER} bin/OpenRA.dll Engine.EngineDir=".." Engine.LaunchPath="${TEMPLATE_LAUNCHER}" "Engine.ModSearchPaths=${MOD_SEARCH_PATHS}" Game.Mod="${MOD_ID}" "$@"
```
Using MacOS Catalina 10.15.4. Any hints how to get it up and running?

**Comment by pchote** [comment]
This is probably https://github.com/OpenRA/OpenRA/issues/19658, which would be fixed here once OpenKrush updates to a newer engine version.

**Comment by wu3ty** [comment]
Thanks @pchote. After running the executable from the latest dmg file, I ran exactly into the issue you described. Do you have any timeline for the update?

**Comment by pchote** [comment]
Try installing mono from https://www.mono-project.com/download/stable/ and compile OpenKrush using `make RUNTIME=mono`. If my guess above is correct then this will provide a workaround until @IceReaper is able to do the engine update.

**Comment by wu3ty** [comment]
Will give it a try over the holidays, thanks mate.
