### ISSUE TITLE
Unable to locate game assets

### ISSUE THREAD

**Issue by Austin28069** [IceReaper/OpenKrush#157]
Hi
I'm so glad that the new version of OpenKrush released recently.
However, I found the problem that the application doesn't work properly even though I installed KKnD via Steam.
And I also tried to reinstall via Steam. It's still not working properly.
I'm not sure if I had wrong process of installation.
Would you please do me a favor to check on it?

Followings are some information about this issue:
KKnD location "D:\SteamLibrary\steamapps\common\Krush Kill 'N Destroy Xtreme"
OpenKrush location "D:\SteamLibrary\steamapps\common\OpenKrush"
OpenKrush version "OpenKrush-playtest-20220219-x64"

![image](https://user-images.githubusercontent.com/89229193/154857066-10265bad-786c-42e5-8fc0-5a39a01b9b15.png)

**Comment by IceReaper** [comment]
Fixed
