### ISSUE TITLE
It seems a sync problem with multiplayer game

### ISSUE THREAD

**Issue by Austin28069** [IceReaper/OpenKrush#163]
![Fatal Error](https://user-images.githubusercontent.com/89229193/160182858-b36c50c3-b949-4e43-b262-94f50be86ced.jpg)

As you can see, I was a host to invite my friend to play KKnD together.
Just started for a little time, he suddenly disconnected and the game crashed.
Here are some logs that he submitted to me. Thank you for your helps.

[exception-2022-03-04T212323Z.log](https://github.com/IceReaper/OpenKrush/files/8353148/exception-2022-03-04T212323Z.log)
[exception-2022-03-25T175733Z.log](https://github.com/IceReaper/OpenKrush/files/8353149/exception-2022-03-25T175733Z.log)
[exception-2022-03-25T180208Z.log](https://github.com/IceReaper/OpenKrush/files/8353150/exception-2022-03-25T180208Z.log)
[exception-2022-03-25T181116Z.log](https://github.com/IceReaper/OpenKrush/files/8353151/exception-2022-03-25T181116Z.log)
[exception-2022-03-25T182749Z.log](https://github.com/IceReaper/OpenKrush/files/8353152/exception-2022-03-25T182749Z.log)
[syncreport-2022-03-25T175733Z.log](https://github.com/IceReaper/OpenKrush/files/8353153/syncreport-2022-03-25T175733Z.log)
[syncreport-2022-03-25T180208Z.log](https://github.com/IceReaper/OpenKrush/files/8353154/syncreport-2022-03-25T180208Z.log)
[syncreport-2022-03-25T181116Z.log](https://github.com/IceReaper/OpenKrush/files/8353155/syncreport-2022-03-25T181116Z.log)
[syncreport-2022-03-25T182749Z.log](https://github.com/IceReaper/OpenKrush/files/8353156/syncreport-2022-03-25T182749Z.log)

**Comment by IceReaper** [comment]
AI related, ai will be completely rebuild from scratch soon.
