### ISSUE TITLE
unable to locate game assets

### ISSUE THREAD

**Issue by Huholoman** [IceReaper/OpenKrush#165]
Hello there,
im trying to get OpenKrush running, but when I start the game it sais "unable to locate game assets". I can find anywhere where the assets are supposed to be or how to specify path to the original game.

I have installed KKnD2 via steam, then I tried to download standalone dig release. and copy the game data to OpenKrush dir.

Can someboy help me, please?

**Comment by Dzierzan** [comment]
Hi,

What's your copy of KKND game? Steam? GoG? Retail?

**Comment by Huholoman** [comment]
I have installed KKnD2 via steam and then ive tried digital copy which ive found on the internet.

**Comment by Dzierzan** [comment]
KKND2 is not supported.

You have to own a legit copy of KKND1 if you wanna use OpenKrush. You can buy it on Steam or GoG. They are often on sale.

**Comment by Huholoman** [comment]
Oh damn. I have the first one too, but i kind of missed the second one is not supported :sob: 

But thanks anyway.
