### ISSUE TITLE
linux content support

### ISSUE THREAD

**Issue by jamerlan** [IceReaper/OpenKrush#18]
I have linux (fedora 29 + wine).
I purchased KKND Extreme from gog website (just to fill this game with music). And then I downloaded setup_kknd_xtreme_2.0.0.9.exe installer. Then I successfully installed it (using wine). 
The installation directory is: ~/.wine/drive_c/GOG Games/KKND Xtreme

How can I specify where this content is located? The game can't find it automagically.

**Comment by IceReaper** [comment]
Adding support for that is planned. Cause osx has the same problem, i need to add mechanics to extract the stuff from the gog installer itself. Cant rely on wine here. The game works without the full game at the moment so it is not the top prioritiy issue but ill properly implement that in the future

**Comment by jamerlan** [comment]
Is there any workaround?
Can I copy 
C:/Documents & Settings/Users/USER/Documents/OpenRA/Content/kknd1
from someone to my
/home/USER/.openra/Content/kknd1
directory? Will it work?

I just did that.. and in "manage content" I have "Installed"  status for both items.. but still I have no music. And when I go to music settings it says: "No music installed".
But maybe I did smth wrong?

**Comment by Mailaender** [comment]
You could use something like [fetch-content.sh](https://github.com/OpenRA/ra2/blob/5bd9e03805570f24058b99146b332d15b814a80a/fetch-content.sh) in the meantime.

**Comment by IceReaper** [comment]
I will implement a file path chooser to manualy select the installation directory in the future
