### ISSUE TITLE
[BUG] Memory leak when a install of KKnD isn't found.

### ISSUE THREAD

**Issue by sirbaratusii** [IceReaper/OpenKrush#180]
Took this screenshot a month before I installed a copy of KKnD Xtreme, when the game couldn't find a install. It would use up more of my RAM for some strange reason. Here's a screenshot of my task manager, it even used more RAM than the web browser (Vivaldi) did.

![image](https://user-images.githubusercontent.com/7905063/230892686-32430b23-e8f9-4117-86c6-159d5a72ea33.png)

- How to reproduce -
Uninstall KKnD Xtreme or install OpenKrush on a machine that doesn't have KKnD Xtreme installed, run it and check the Task Manager.

**Comment by IceReaper** [comment]
Thanks for reporting. This bug is already fixed in git, and only applies to our last release. Will close the issue. Will be fixed in the next release build
