### ISSUE TITLE
How to install assets on linux?

### ISSUE THREAD

**Issue by segatrade** [IceReaper/OpenKrush#181]
Tried CD mount. Also have GoG. Nothing helped. To what path I need copy assets? What files?

**Comment by IceReaper** [comment]
The english cd (dos as well as xtreme) should work. For the GoG version, we currently have no support to properly detect it somewhere under linux. Steam on the other hands works. Alternatively, one could always manualy copy the files into the destination dir. See the paths here: https://github.com/IceReaper/OpenKrush/blob/master/mods/openkrush_gen1/installer/gog.yaml
Need to redo this part in the future for even further game detection support.

**Comment by pasnox** [comment]
where should we copy those files ?

**Comment by segatrade** [comment]
I used this one https://github.com/IceReaper/OpenKrush/blob/master/mods/openkrush_gen1/installer/kknd_english.yaml and it works

@pasnox from yaml example: `^SupportDir|Content/openkrush_gen1/music/surv1.wav: KKND/LEVELS/SURV1.SON`
CAPS locked it's original path. And left part - where to copy. This file extension also need to be changed
On my pc it's: `/home/usr0/.config/openra/Content/openkrush_gen1`

Game started I play, but get crash when load a savegame
Looks nice. But miss some good stuff from openra - attack lines. Also In Shattered Paradise or Romanov Venegence nice unit stats and select. Also stance - hold fire, attack etc

**Comment by pasnox** [comment]
It's where i put my files but the appimage still say it can't find the assets ?

> find $HOME/.config/openra/Content/openkrush_gen1/
> /home/thriwien/.config/openra/Content/openkrush_gen1/
> /home/thriwien/.config/openra/Content/openkrush_gen1/sprites.lvl
> /home/thriwien/.config/openra/Content/openkrush_gen1/mute.slv
> /home/thriwien/.config/openra/Content/openkrush_gen1/surv.slv
> /home/thriwien/.config/openra/Content/openkrush_gen1/music
> /home/thriwien/.config/openra/Content/openkrush_gen1/music/mute1.wav
> /home/thriwien/.config/openra/Content/openkrush_gen1/music/mute2.wav
> /home/thriwien/.config/openra/Content/openkrush_gen1/music/mute3.wav
> /home/thriwien/.config/openra/Content/openkrush_gen1/music/surv1.wav
> /home/thriwien/.config/openra/Content/openkrush_gen1/music/surv2.wav
> /home/thriwien/.config/openra/Content/openkrush_gen1/music/surv3.wav
> /home/thriwien/.config/openra/Content/openkrush_gen1/fmv
> /home/thriwien/.config/openra/Content/openkrush_gen1/fmv/headm01.vbc
> /home/thriwien/.config/openra/Content/openkrush_gen1/fmv/evolvout.vbc
> /home/thriwien/.config/openra/Content/openkrush_gen1/fmv/headm02.vbc
> /home/thriwien/.config/openra/Content/openkrush_gen1/fmv/headm03.vbc
> /home/thriwien/.config/openra/Content/openkrush_gen1/fmv/headm04.vbc
> /home/thriwien/.config/openra/Content/openkrush_gen1/fmv/headm05.vbc
> /home/thriwien/.config/openra/Content/openkrush_gen1/fmv/headm06.vbc
> /home/thriwien/.config/openra/Content/openkrush_gen1/fmv/headm07.vbc
> /home/thriwien/.config/openra/Content/openkrush_gen1/fmv/headm08.vbc
> /home/thriwien/.config/openra/Content/openkrush_gen1/fmv/headm09.vbc
> /home/thriwien/.config/openra/Content/openkrush_gen1/fmv/headm10.vbc
> /home/thriwien/.config/openra/Content/openkrush_gen1/fmv/headm11.vbc
> /home/thriwien/.config/openra/Content/openkrush_gen1/fmv/headm12.vbc
> /home/thriwien/.config/openra/Content/openkrush_gen1/fmv/headm13.vbc
> /home/thriwien/.config/openra/Content/openkrush_gen1/fmv/headm14.vbc
> /home/thriwien/.config/openra/Content/openkrush_gen1/fmv/headm15.vbc
> /home/thriwien/.config/openra/Content/openkrush_gen1/fmv/heads01.vbc
> /home/thriwien/.config/openra/Content/openkrush_gen1/fmv/heads02.vbc
> /home/thriwien/.config/openra/Content/openkrush_gen1/fmv/heads03.vbc
> /home/thriwien/.config/openra/Content/openkrush_gen1/fmv/heads04.vbc
> /home/thriwien/.config/openra/Content/openkrush_gen1/fmv/heads05.vbc
> /home/thriwien/.config/openra/Content/openkrush_gen1/fmv/heads06.vbc
> /home/thriwien/.config/openra/Content/openkrush_gen1/fmv/heads07.vbc
> /home/thriwien/.config/openra/Content/openkrush_gen1/fmv/heads08.vbc
> /home/thriwien/.config/openra/Content/openkrush_gen1/fmv/heads09.vbc
> /home/thriwien/.config/openra/Content/openkrush_gen1/fmv/heads10.vbc
> /home/thriwien/.config/openra/Content/openkrush_gen1/fmv/heads11.vbc
> /home/thriwien/.config/openra/Content/openkrush_gen1/fmv/heads13.vbc
> /home/thriwien/.config/openra/Content/openkrush_gen1/fmv/heads14.vbc
> /home/thriwien/.config/openra/Content/openkrush_gen1/fmv/heads12.vbc
> /home/thriwien/.config/openra/Content/openkrush_gen1/fmv/heads15.vbc
> /home/thriwien/.config/openra/Content/openkrush_gen1/fmv/intro.vbc
> /home/thriwien/.config/openra/Content/openkrush_gen1/fmv/mh_fmv.vbc
> /home/thriwien/.config/openra/Content/openkrush_gen1/fmv/survout.vbc
