### ISSUE TITLE
Random sound pitch

### ISSUE THREAD

**Issue by Dzierzan** [IceReaper/OpenKrush#68]
This is an idea. By default, beast units in KKND have two sounds, one for selecting, the other for action.  Thus it becomes quickly tedious. My idea is that KKND (OpenRA Engine in general) could use some sort of random sound pitch for selected sounds. Of course such pitch shouldn't be too huge so the sound won't be too much distorted.

**Comment by GraionDilach** [comment]
Just FYI: RA2 used a 10% pitch shifting on most weapon audio effect and 4% pitch shifting on dog responses for this reason.

**Comment by Dzierzan** [comment]
Cool, how was it done?

**Comment by GraionDilach** [comment]
It was an engine effect, part of the sound engine there. I'm not sure if it was debugged properly because the sound engine was rewritten for RA2. I presume the way tracker music does it is fine though.
