### ISSUE TITLE
stuff hidden by fog should not animate

### ISSUE THREAD

**Issue by IceReaper** [IceReaper/OpenKrush#91]
Buildings are playing their animation when covered by fog. Should not be like this.

**Comment by Dzierzan** [comment]
The question is, should enemy buildings be still visable after they were scouted? Or disappear behind the fog.

**Comment by Dzierzan** [comment]
I've been testing that. It seems that buildings are frozen under the fog. You need to test it again.

**Comment by IceReaper** [comment]
Wonder if we can hack that on dying actors

**Comment by IceReaper** [comment]
Fixed in openra.
